FROM golang:1.21.2-alpine

RUN apk update && apk upgrade && \
    apk add git make curl openssh-client

# Cria um diretório para o projeto
WORKDIR /app

# Copia todo o projeto para o contêiner
COPY . .

# Instala o air para desenvolvimento
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air


CMD air start
