version: '3.8'

x-services-defaults: &defaults
  restart: on-failure
  networks:
    - school-management
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  db:
    <<: *defaults
    image: postgres:15
    container_name: school-management-db
    tty: true
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  api:
    <<: *defaults
    container_name: school-management-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

networks:
  school-management: {}

volumes:
  postgres: {}
